language: node_js
node_js:
- 5.0.0
before_deploy:
- npm run demo
deploy:
  provider: heroku
  api_key:
    secure: A7uQeJ11uO+YldoMZClRfvAVK8JLd1DsPVYRjeo6azH6y65S94Cr/IYURIvV1NDhTlt1J8Aeax6y2avR3pg1DtJUkuIQk91rM2Gx/xw1reYJC1Z1haKdbHRnDFpqRvG7vM6mTYKM6GP7Gr1jAZEATiXVns9XSPFiXxDb5M8qD4A=
  skip_cleanup: true
